### ISSUE TITLE
Crashes on start when OpenTrack is not installed

### ISSUE THREAD

**Issue by IzzySoft** [OpenTracksApp/OSMDashboard#10]
I just installed your app on my test device (running Android 6.0.1 / LOS). It crashes right on start (when OpenTracks itself is not installed):

```log
01-24 22:34:57.987 31214 31214 W System  : ClassLoader referenced unknown path: /data/app/de.storchp.opentracks.osmplugin-1/lib/arm
01-24 22:34:58.054 31214 31214 D AndroidRuntime: Shutting down VM
01-24 22:34:58.057 31214 31214 E AndroidRuntime: FATAL EXCEPTION: main
01-24 22:34:58.057 31214 31214 E AndroidRuntime: Process: de.storchp.opentracks.osmplugin, PID: 31214
01-24 22:34:58.057 31214 31214 E AndroidRuntime: Theme: themes:{}
01-24 22:34:58.057 31214 31214 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.storchp.opentracks.osmplugin/de.storchp.opentracks.osmplugin.MainActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:596)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.app.Activity.onApplyThemeResource(Activity.java:3737)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:150)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:94)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setTheme(AppCompatActivity.java:111)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2396)
01-24 22:34:58.057 31214 31214 E AndroidRuntime: 	... 9 more
```

On a different device (running Android 8.1), it starts up fine showing a hint on the missing app. But there, that hint is even displayed after installing OpenTracks. And even when installed in "opposite order" (first OpenTracks, then the plugin).

**Comment by dennisguse** [comment]
The installation order should not be relevant as OSMDashboard actually is a separate app that gets temporary access to OpenTracks resources.
@IzzySoft do you have some more info about the device?

**Comment by IzzySoft** [comment]
Sure. What details do you need for which of the two devices mentioned? For the 8.1 device, [see here](https://github.com/IzzySoft/Adebar/wiki/example-deviceInfo.md). I could generate the same for the 6.0 device (where the app crashes on) if that would help you. If you prefer the "raw data" (`dumpsys` etc), just let me know which and where to put it. I could also zip it up as [dummy device](https://github.com/IzzySoft/Adebar/wiki/Dummy-Devices) so you could generate the docu yourself :wink:

**Comment by pstorch** [comment]
That's a strange error. I don't see any hard dependencies to the main App. Let's see if we can reproduce it.

**Comment by pstorch** [comment]
I could reproduce it on an emulator with Android 6.0. It seems to be the opaque setting in the primary colour:

https://stackoverflow.com/questions/29166809/5-1-crash-a-taskdescriptions-primary-color-should-be-opaque

**Comment by IzzySoft** [comment]
Well, the important part is it no longer crashes (and thus scares new users away). Thanks for fixing it that fast, Peter!
