### ISSUE TITLE
To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OSMDashboard#130]
I can't use app in Android 12. Here logs:

```log
2021-12-03 23:58:55.723 28290-28290/de.storchp.opentracks.osmplugin.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.storchp.opentracks.osmplugin.debug, PID: 28290
    java.lang.RuntimeException: Unable to resume activity {de.storchp.opentracks.osmplugin.debug/de.storchp.opentracks.osmplugin.MapsActivity}: java.lang.SecurityException: To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4757)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4790)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.SecurityException: To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.
        at android.hardware.SystemSensorManager$BaseEventQueue.enableSensor(SystemSensorManager.java:792)
        at android.hardware.SystemSensorManager$BaseEventQueue.addSensor(SystemSensorManager.java:712)
        at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:209)
        at android.hardware.SensorManager.registerListener(SensorManager.java:832)
        at android.hardware.SensorManager.registerListener(SensorManager.java:739)
        at de.storchp.opentracks.osmplugin.compass.AbstractLowPassSensor.startImpl(AbstractLowPassSensor.java:58)
        at de.storchp.opentracks.osmplugin.compass.AbstractSensor.start(AbstractSensor.java:19)
        at de.storchp.opentracks.osmplugin.compass.Compass.startImpl(Compass.java:95)
        at de.storchp.opentracks.osmplugin.compass.AbstractSensor.start(AbstractSensor.java:19)
        at de.storchp.opentracks.osmplugin.MapsActivity.onResume(MapsActivity.java:762)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1476)
        at android.app.Activity.performResume(Activity.java:8191)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4747)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4790) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7838) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by pstorch** [comment]
@rgmf can you test the next nightly with provided the fix?

**Comment by rgmf** [comment]
@pstorch Yes, it works ;)
