### ISSUE TITLE
When clicking on the map icon of any track, it's throwing the error 

### ISSUE THREAD

**Issue by UIcoder511** [OpenTracksApp/OSMDashboard#306]
### App information
* ID: de.storchp.opentracks.osmplugin.debug
* Version: 38 2.22.2
* Build flavor: full

### Device information
* Brand: samsung
* Device: r8q
* Model: SM-G781B
* Id: TP1A.220624.014
* Product: r8qxxx

### Firmware
* SDK: 33
* Release: 13
* Incremental: G781BXXS8HWJ1

### Cause of error
```java
Exception in thread "main": java.lang.RuntimeException: Unable to start activity ComponentInfo{de.storchp.opentracks.osmplugin.debug/de.storchp.opentracks.osmplugin.MapsActivity}: java.lang.RuntimeException: Error reading trackpoints
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.RuntimeException: Error reading trackpoints
	at de.storchp.opentracks.osmplugin.MapsActivity.readTrackpoints(MapsActivity.java:630)
	at de.storchp.opentracks.osmplugin.MapsActivity.onNewIntent(MapsActivity.java:196)
	at de.storchp.opentracks.osmplugin.MapsActivity.onCreate(MapsActivity.java:172)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Source and Destination cannot be null
	at de.storchp.opentracks.osmplugin.utils.MapUtils.bearing(MapUtils.java:146)
	at de.storchp.opentracks.osmplugin.utils.MapUtils.bearingInDegrees(MapUtils.java:159)
	at de.storchp.opentracks.osmplugin.maps.MovementDirection.updatePos(MovementDirection.java:14)
	at de.storchp.opentracks.osmplugin.MapsActivity.readTrackpoints(MapsActivity.java:613)
	... 18 more

```

**Comment by dennisguse** [comment]
Which OpenTracks version?

**Comment by UIcoder511** [comment]
4.9.4

**Comment by UIcoder511** [comment]
It is now resolved. There were unnecessary changes in our fork
