### ISSUE TITLE
Feature request: Open GPX files from file manager

### ISSUE THREAD

**Issue by RealVegOs** [OpenTracksApp/OSMDashboard#392]
I want to use this cute app as a general purpose GPX viewer, not only as companion for OpenTracks. I have a lot of routes on my WiFi tablet I created with a GPX editor on my PC. On Android it lacks a quick GPX viewer to check routes for a possible hike. Of course I could open them with a navigation App like Organic Maps or AAT but this is too slow. Organic Maps even saves the route as bookmark, without asking. So please let OSMDashboard tell Android that it can open GPX files. Thanks for any consideration.

Another option would be to add a file choosing dialog to OSMDashboard, but I prefer the file manager.

**Comment by pstorch** [comment]
@RealVegOs can be tested in the latest nightly build.

**Comment by RealVegOs** [comment]
THX! But I have no clue, how this works now. Can't share or open with. Nightly is not listed.

**Comment by RealVegOs** [comment]
Fossify File Manager

**Comment by pstorch** [comment]
I see, it's not working with that app. Need to find out why.

**Comment by pstorch** [comment]
Looks like Fossify File Manager announces gpx files differently, but I could get it to work. With the next nightly it should be visible as a share target.

**Comment by RealVegOs** [comment]
Now this:

 ### Cause of error
            ```java
            Exception in thread "main": java.lang.RuntimeException: Unable to start activity ComponentInfo{de.storchp.opentracks.osmplugin.nightly/de.storchp.opentracks.osmplugin.map.MapsActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3712)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3849)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        ...
        ...
        ...

**Comment by pstorch** [comment]
Hmm, do you have the complete stacktrace? There seems to be something missing. 
Or an example gpx file which causes this error? 
From which application is the gpx file? Have you tried a gpx file which was exported from OpenTracks?

**Comment by RealVegOs** [comment]
I took some time and played with a greater number of gpx files. Most tracks work, gpx routes cause to show me nothing except the ocean and continents. I used different gpx editors but for the last two years it was JGPSTrackEdit. So don't mind about the Java error above. Excuse me for having filed it. Would it be possible to support routes too? Then this dashboard would be a perfect stand alone gpx viewer. Thanks for any consideration.

**Comment by pstorch** [comment]
Thanks for your extended tests. Can you provide me a gpx file with routes?

**Comment by RealVegOs** [comment]
[test-route.txt](https://github.com/user-attachments/files/18332273/test-route.txt)
I had to rename the extension. It's a gpx file of course.

**Comment by RealVegOs** [comment]
I just tested the nightly. It's really nice. Thank you very much! It's a rather quick method to check gpx files without a pc. I can do it outdoors on my tablet. There is one file, messing again with the Java error. It was digested by GPSBabel I think. I attach it, but you may ignore it. Normally I draw my routes and do not convert them. 
[biesdorf-7.0km-route.txt](https://github.com/user-attachments/files/18338762/biesdorf-7.0km-route.txt)

**Comment by pstorch** [comment]
Thanks for the testfile. The routpoints had no elevation. I made it optional now, so this file can be read as well.

**Comment by RealVegOs** [comment]
Excellent!

**Comment by RealVegOs** [comment]
Sorry for waking this up again. One more glitch: Statistics do not work for drawn routes. At least they should yield a distance. For recorded tracks it works.

**Comment by pstorch** [comment]
You are right. For these I would need to calculate the distance myself. In tracks it's already calculated. 
I'll look into it.

**Comment by RealVegOs** [comment]
What about disabling statistics if nothing is calulated at all? That's the case with tracks from other apps than Open Tracks.
See here a track with all data recorded with AAT App.
[2024_04_27_17_01.txt](https://github.com/user-attachments/files/18431054/2024_04_27_17_01.txt)

**Comment by pstorch** [comment]
Then I would need to distinguish between 0 and null. But could be possible. I'll check. 
Thanks for the new sample.

**Comment by pstorch** [comment]
@RealVegOs you can check out the new nightly build, if you want. I'm thinking about a release of this version at the weekend.

**Comment by RealVegOs** [comment]
I texted last night and I like it.
