### ISSUE TITLE
Crash in "online map consent" dialog 

### ISSUE THREAD

**Issue by vanek49** [OpenTracksApp/OSMDashboard#434]
### App information
* ID: de.storchp.opentracks.osmplugin
* Version: 45 5.0.0
* Build flavor: full

### Device information
* Brand: Xiaomi
* Device: apollo
* Model: M2007J3SG
* Id: SKQ1.211006.001
* Product: apollopro_global

### Firmware
* SDK: 31
* Release: 12
* Incremental: V14.0.1.0.SJDMIXM

### Cause of error
```java
Exception in thread "main": java.lang.RuntimeException: Unable to start activity ComponentInfo{de.storchp.opentracks.osmplugin/de.storchp.opentracks.osmplugin.map.MapsActivity}: java.lang.NullPointerException: An AlertDialog must have a TextView with id.message
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3763)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3937)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.NullPointerException: An AlertDialog must have a TextView with id.message
	at java.util.Objects.requireNonNull(Objects.java:232)
	at de.storchp.opentracks.osmplugin.map.MapsActivity.showOnlineMapConsent(MapActivity.kt:529)
	at de.storchp.opentracks.osmplugin.map.MapsActivity.createLayers(MapActivity.kt:487)
	at de.storchp.opentracks.osmplugin.map.MapsActivity.onCreate(MapActivity.kt:149)
	at android.app.Activity.performCreate(Activity.java:8241)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3736)
	... 12 more

```

**Comment by pstorch** [comment]
Thanks for reporting. Looks like the "online map consent" dialog is broken. 

Until it's fixed, you can workaround this by starting OSMDashboard standalone, go to settings and activate the online map consent setting or choose an offline map.
