### ISSUE TITLE
[CRASH] IllegalArgumentException: invalid latitude: NaN

### ISSUE THREAD

**Issue by ildar** [OpenTracksApp/OSMDashboard#9]
opening EMPTY track with an offline map
```
01-24 11:28:55.828  4011  4031 E AndroidRuntime: FATAL EXCEPTION: LayerManager
01-24 11:28:55.828  4011  4031 E AndroidRuntime: Process: de.storchp.opentracks.osmplugin, PID: 4011
01-24 11:28:55.828  4011  4031 E AndroidRuntime: java.lang.IllegalArgumentException: invalid latitude: NaN
01-24 11:28:55.828  4011  4031 E AndroidRuntime: 	at org.mapsforge.core.util.LatLongUtils.validateLatitude(LatLongUtils.java:305)
01-24 11:28:55.828  4011  4031 E AndroidRuntime: 	at org.mapsforge.core.model.BoundingBox.<init>(BoundingBox.java:72)
01-24 11:28:55.828  4011  4031 E AndroidRuntime: 	at org.mapsforge.map.util.MapPositionUtil.getBoundingBox(MapPositionUtil.java:46)
01-24 11:28:55.828  4011  4031 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:89)
01-24 11:28:55.828  4011  4031 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
01-24 11:28:55.832  5093  7543 W ActivityManager:   Force finishing activity de.storchp.opentracks.osmplugin/.MapsActivity
```

**Comment by pstorch** [comment]
Thanks for the report. I can reproduce it. I'll have a look.
